name: Lint Code with Flake8

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-html

    - name: Run Flake8
      run: |
        mkdir -p flake8-report
        flake8 --format=html --htmldir=flake8-report || true

    - name: Upload Flake8 report
      uses: actions/upload-artifact@v2
      with:
        name: flake8-report
        path: flake8-report
